# Generated by Django 2.2 on 2019-09-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='post',
            name='votes',
        ),
    ]
